### PR TITLE
Roll and Ship

### PR DESCRIPTION
**Pull request by NRPGamer**
Compiled and ran fine for me, notify me of any errors

### CODE REVIEW

**Comment by NRPGamer** [comment]
I wasn't certain of how to do so without modification of trollegle.messages; I agree that the usage strings are a needed addition but did not work out how to add them, explaining their absence in the request.

**Comment by TruelyThea** [comment]
You might not need to convert `target1` and `target2` in `/ship` to `ExtendedCaptchaUser`s

Could you replace the redundant code in `ExtendedBotBehavior` with something like this (once it works--it might already)

    String[] names = {"hug", "pat", "stab", "appear", "magic", "flip", "roll", "ship", "shrug", "tell", "do", "say"};
    for (int i = 0; i < names.length; i++) {
        String name = names[i];
        Command command = b.getCommand(name);
        addMyCommand(name, command, null, command.usage);
    }

We haven't added any aliases for the new commands right?

**Comment by TruelyThea** [comment]
For how to add the usage, I think you can just add it as the last argument to `addMyCommand`

**Comment by TruelyThea** [comment]
Okay, I think that the `==` check will still work, it's something you can easily test with a few `/ship` calls after compiling and running the room.

**Comment by TruelyThea** [comment]
Okay, it looks good :blush:

**Pull request merged**
